//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friends_from_MegaVideo_player.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Friends_from_MegaVideo_player.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Icon back_arrowICO {
            get {
                object obj = ResourceManager.GetObject("back_arrowICO", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon Forward_ArrowICO {
            get {
                object obj = ResourceManager.GetObject("Forward_ArrowICO", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        ///&lt;!--Autor: Łukasz Sypniewski--&gt;
        ///&lt;!--Katalog odcinkow Przyjaciol� z linkami do nich--&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;Przyjaciele.xsl&quot;?&gt;
        ///&lt;Spis&gt;
        ///  &lt;Odcinek&gt;
        ///    &lt;NazwaOdcinka&gt;The One Where Monica Gets a Roommate&lt;/NazwaOdcinka&gt;
        ///    &lt;Sezon&gt;1&lt;/Sezon&gt;
        ///    &lt;NrWSezonie&gt;1&lt;/NrWSezonie&gt;
        ///    &lt;NrOgolnie&gt;1&lt;/NrOgolnie&gt;
        ///    &lt;Link&gt;http://www.megavideo.com/v/PPU85N0Sc2c6f227fade21db7d2a9467137f92e7&lt;/Link&gt;
        ///  &lt;/Odcinek&gt;
        ///  &lt;Odcinek&gt;
        ///    &lt;NazwaOdcinka&gt;The One with  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Friends___lista_odcinków {
            get {
                return ResourceManager.GetString("Friends___lista_odcinków", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Friends_logo {
            get {
                object obj = ResourceManager.GetObject("Friends_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon Friends_Player_Icon {
            get {
                object obj = ResourceManager.GetObject("Friends_Player_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static byte[] Icons {
            get {
                object obj = ResourceManager.GetObject("Icons", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
